### ISSUE TITLE
Plugin doesn't load. No error message.

### ISSUE THREAD

**Issue by dabunginator** [PancakeTAS/obs-nvfbc-v30#6]
I'm using Linux Mint 22 (Cinnamon), & I installed OBS (OBS 30.0.2.1-3build1) from my package manager. My plugin directory is `/lib/x86_64-linux-gnu/obs-plugins`. I placed the .so file into there, but when I go to add a source in OBS, the plugin isn't there.

**Comment by PancakeTAS** [comment]
Launch and immediately close obs with `obs --verbose` and send the log please.
The plugin does not work right now due to recent driver updates, but it entirely not loading seems like another issue worth looking at.

**Comment by dabunginator** [comment]
I'm using the OBS Flatpak now (30.2.3). It seems that OBS doesn't recognize obs-nvfbc as an OBS plugin. (I don't know if this matters, but when I ran `make`, the resulting file was named `preload.so`. I renamed it to `obs-nvfbc.so`.)

Log:
https://pastebin.com/Jq0PiPrN

**Comment by PancakeTAS** [comment]
Ah, I see the problem. The preload.so is supposed to be preloaded using LD_PRELOAD. It's supposed to create another file but I guess I messed up the Makefile.

Run `make obs-nvfbc.so` as well and copy that into your plugins directory instead.
Then run obs with `LD_PRELOAD=<full path to preload.so> obs` which will actually load the plugin.

Again though, you won't get a working source as recent driver changes have broken stuff and NVIDIA is yet to release the new capture sdk

**Comment by dabunginator** [comment]
Thank you.
