### ISSUE TITLE
preload.so is being compiled instead of obs-nvfbc.so

### ISSUE THREAD

**Issue by toboil-features** [PancakeTAS/obs-nvfbc-v30#7]
Although README.md tells about obs-nvfbc.so

**Comment by PancakeTAS** [comment]
Read through #6, the README is not up-to-date

**Comment by toboil-features** [comment]
So will it be updated? If I'll update it by pull request, would you accept it?

**Comment by PancakeTAS** [comment]
I will update the README.md myself, as the project will likely get a major refactor after NVIDIA finally releases the new Capture SDK
